on: issue_comment
name: test-kata-deploy
jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: kata-containers/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: "test"
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
      - name: verify command arg is kata-deploy
        run: |
           echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
           [[ ${{ steps.command.outputs.command-arguments}} == "kata-deploy" ]]
  create-and-test-container:
    needs: check_comments
    runs-on: ubuntu-latest
    steps:
      - name: get-PR-ref
        id: get-PR-ref
        run: |
            ref=$(cat $GITHUB_EVENT_PATH | jq -r '.issue.pull_request.url' | sed  's#^.*\/pulls#refs\/pull#' | sed 's#$#\/merge#')
            echo "reference for PR: " ${ref}
            echo "##[set-output name=pr-ref;]${ref}"
      - uses: actions/checkout@v2-beta
        with:
          ref: ${{ steps.get-PR-ref.outputs.pr-ref }}
      - name: build-container-image
        id: build-container-image
        run: |
            echo hello
